services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_USER: planify
      POSTGRES_PASSWORD: planify
      POSTGRES_DB: planify
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planify"]
      interval: 5s
      timeout: 5s
      retries: 5

  main:
    hostname: main
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://planify:planify@postgres:5432/planify
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - .:/app
    command: bash

volumes:
  postgres_data:
    driver: local
