name: CI
  on:
    push:
      branches:
        - main
        - 'Release-*'
        - 'DEV-*'
    pull_request:
      branches:
        - main
        - 'Release-*'
        - 'DEV-*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - planifyFront
          - planifyAPI
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Compile ./${{ matrix.dir }} package
        working-directory: ./${{ matrix.dir }}
        run: mvn -B package --file pom.xml
      - name: Test ./${{ matrix.dir }} package
        working-directory: ./${{ matrix.dir }}
        run: mvn test

  frontend: