name: Java CI with Maven

# Disparadores (triggers) para el workflow
on:
  push:
    branches:
      - main # Ejecuta en la rama main
      - 'DEV-*'
      - 'RELEASE-*'
  pull_request:
    branches:
      - main # Ejecuta cuando se cree un pull request hacia la rama main
      - 'DEV-*'
      - 'RELEASE-*'

# Configuración de los jobs
jobs:
  build:
    runs-on: ubuntu-latest # Usa la última versión de Ubuntu para ejecutar los tests

    # Pasos para el job
    steps:
      # Paso 1: Verificar el código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar Java
      - name: Set up JDK 21 # O la versión que necesites
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Asegúrate de que sea la versión que necesitas
          distribution: 'temurin'

      # Paso 4: Instalar dependencias y ejecutar pruebas
      - name: Install dependencies
        run: mvn -f planifyAPI/pom.xml --batch-mode --update-snapshots verify

      # Paso 5: Subir artefactos o generar reportes si es necesario
      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: planifyAPI/test/TestRes/ # O la ubicación de los reportes de tus pruebas
