name: CI

on:
  push:
    branches:
      - 'DEV-*'
      - release
      - main
  pull_request:
    branches:
      - 'DEV-*'
      - release
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: planifydb
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Compile package
      working-directory: ./planifyAPI
      run: mvn clean package
    - name: Test package
      working-directory: ./planifyAPI
      run: mvn test